//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BunchofBrackets.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBracket
    {
        public System.Guid Id { get; set; }
        public System.Guid ModeratorId { get; set; }
        public string Name { get; set; }
        public string ImageSource { get; set; }
        public string Game { get; set; }
        public int OriginalRoundCount { get; set; }
        public int CurrentDivision { get; set; }
    }
}
