//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BunchofBrackets.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFriend
    {
        public System.Guid Id { get; set; }
        public System.Guid User1Id { get; set; }
        public System.Guid User2Id { get; set; }
        public System.DateTime FriendDate { get; set; }
    }
}
