//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BunchofBrackets.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMatch
    {
        public System.Guid Id { get; set; }
        public System.Guid Team1 { get; set; }
        public Nullable<System.Guid> Team2 { get; set; }
        public Nullable<System.Guid> Outcome { get; set; }
        public System.Guid BracketId { get; set; }
        public Nullable<System.Guid> ReportingPlayer { get; set; }
        public int Round { get; set; }
        public int Division { get; set; }
    }
}
