CREATE TABLE [dbo].[tblFriend]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [User1Id] UNIQUEIDENTIFIER NOT NULL, 
    [User2Id] UNIQUEIDENTIFIER NOT NULL, 
    [FriendDate] DATETIME NOT NULL
)
