CREATE TABLE [dbo].[tblMatch]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Team1] UNIQUEIDENTIFIER NOT NULL, 
    [Team2] UNIQUEIDENTIFIER NULL, 
    [Outcome] UNIQUEIDENTIFIER NULL, 
    [BracketId] UNIQUEIDENTIFIER NOT NULL, 
    [ReportingPlayer] UNIQUEIDENTIFIER NULL, 
    [Round] INT NOT NULL, 
    [Division] INT NOT NULL
)
